config/routes.rb
Soso::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :language_grades

  get 'profile/password'
  get 'faculties/field_of_studies/:faculty_id', to: 'faculties#field_of_studies', as: :faculties_field_of_studies
  get 'faculties/specializations/:field_of_study_id', to: 'faculties#specializations', as: :faculties_specializations

  resources :faqs do
    collection do
      post 'sort'
    end
  end

  root to: 'pages#root'

  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :registration,
             only: [:new, :create, :edit, :update],
             path: 'users',
             path_names: {new: 'sign_up'},
             controller: 'devise/registrations',
             as: :user_registration do
      get :cancel
    end
  end

  resources :users do
    resources :subject_grades do
      collection do
        post 'sort'
        get 'edit'
      end
    end
    resources :language_grades do
      collection do
        post 'enroll', to: 'users#create', as: :enroll
        patch 'lock', as: :lock
        get 'skip', as: :skip

        # staff
        get 'payment'
        patch 'pay'
      end
    end
    resources :exams do
      collection do
        patch 'lock', as: :lock
      end
      member do
        patch 'sign_up'
        patch 'release'
      end
    end
    patch 'lock', to: 'users#lock', as: :data_lock
    patch 'unlock', to: 'users#unlock', as: :data_unlock

    # staff
    patch :confirm_grades, as: :confirm_grades
    patch :disapprove_grades, as: :disapprove_grades
  end

  get 'p/:slug', to: 'pages#show', as: :page
end

app/models/committee.rb
# == Schema Information
# Schema version: 20130817211608
#
# Table name: committees
#
# *id*::      <tt>integer, not null, primary key</tt>
# *name*::    <tt>string(255), not null, indexed => [city_id]</tt>
# *code*::    <tt>string(255)</tt>
# *city_id*:: <tt>integer, indexed, indexed => [name]</tt>
#
# Indexes
#
#  index_committees_on_city_id           (city_id)
#  index_committees_on_city_id_and_name  (city_id,name) UNIQUE
#--
# == Schema Information End
#++

class Committee < ActiveRecord::Base
  delegate :country, to: :city, allow_nil: true
  belongs_to :city
  has_many :users
  # has_many :news
  # has_many :faqs
  # has_many :appointment
  has_many :faculties
  has_and_belongs_to_many :languages
  has_many :exams

  validates :name,
            presence: true,
            uniqueness: {scope: :city_id}
  validates :city_id,
            presence: true,
            numericality: {only_integer: true}
end

app/models/sector_group.rb
# == Schema Information
# Schema version: 20130820123421
#
# Table name: sector_groups
#
# *id*::   <tt>integer, not null, primary key</tt>
# *name*:: <tt>string(255), indexed</tt>
#
# Indexes
#
#  index_sector_groups_on_name  (name) UNIQUE
#--
# == Schema Information End
#++

class SectorGroup < ActiveRecord::Base
  has_many :sectors

  validates :name,
            presence: true,
            uniqueness: {case_sensitive: false}
end

app/models/user.rb
# == Schema Information
# Schema version: 20130830004029
#
# Table name: users
#
# *id*::                     <tt>integer, not null, primary key</tt>
# *name*::                   <tt>string(50), not null</tt>
# *surname*::                <tt>string(50), not null</tt>
# *email*::                  <tt>string(200), not null, indexed</tt>
# *encrypted_password*::     <tt>string(255), default(""), not null</tt>
# *reset_password_token*::   <tt>string(255), indexed</tt>
# *reset_password_sent_at*:: <tt>datetime</tt>
# *remember_created_at*::    <tt>datetime</tt>
# *sign_in_count*::          <tt>integer, default(0)</tt>
# *current_sign_in_at*::     <tt>datetime</tt>
# *last_sign_in_at*::        <tt>datetime</tt>
# *current_sign_in_ip*::     <tt>string(255)</tt>
# *last_sign_in_ip*::        <tt>string(255)</tt>
# *confirmation_token*::     <tt>string(255), indexed</tt>
# *confirmed_at*::           <tt>datetime</tt>
# *confirmation_sent_at*::   <tt>datetime</tt>
# *unconfirmed_email*::      <tt>string(255)</tt>
# *failed_attempts*::        <tt>integer, default(0)</tt>
# *unlock_token*::           <tt>string(255), indexed</tt>
# *locked_at*::              <tt>datetime</tt>
# *created_at*::             <tt>datetime</tt>
# *updated_at*::             <tt>datetime</tt>
# *role_id*::                <tt>integer, indexed</tt>
# *study_year*::             <tt>integer</tt>
# *birth_date*::             <tt>date</tt>
# *student_no*::             <tt>string(255), indexed => [committee_id]</tt>
# *street*::                 <tt>string(255)</tt>
# *house*::                  <tt>string(255)</tt>
# *city*::                   <tt>string(255)</tt>
# *zip*::                    <tt>string(255)</tt>
# *phone*::                  <tt>string(255)</tt>
# *committee_id*::           <tt>integer, indexed, indexed => [student_no]</tt>
# *field_of_study_id*::      <tt>integer, indexed</tt>
# *specialization_id*::      <tt>integer, indexed</tt>
# *faculty_id*::             <tt>integer, indexed</tt>
# *state*::                  <tt>string(255), default("registered"), not null</tt>
#
# Indexes
#
#  index_users_on_committee_id                 (committee_id)
#  index_users_on_committee_id_and_student_no  (committee_id,student_no) UNIQUE
#  index_users_on_confirmation_token           (confirmation_token) UNIQUE
#  index_users_on_email                        (email) UNIQUE
#  index_users_on_faculty_id                   (faculty_id)
#  index_users_on_field_of_study_id            (field_of_study_id)
#  index_users_on_reset_password_token         (reset_password_token) UNIQUE
#  index_users_on_role_id                      (role_id)
#  index_users_on_specialization_id            (specialization_id)
#  index_users_on_unlock_token                 (unlock_token) UNIQUE
#--
# == Schema Information End
#++

class User < ActiveRecord::Base
  attr_accessor :priority_orphans
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

  belongs_to :committee
  belongs_to :role

  belongs_to :faculty
  belongs_to :field_of_study
  belongs_to :specialization
  has_many :sector_priorities, autosave: true
  validates_associated :sector_priorities
  after_save :clear_orphaned_priorities

  def set_priorities(priorities, validate=true)
    sps = self.sector_priorities
    self.priority_orphans = [] if self.priority_orphans.nil?
    self.priority_orphans = (priority_orphans + sps - priorities).to_a
    self.sector_priorities = priorities
  end

  has_many :subject_grades
  has_many :subjects, through: :subject_grades

  #has_and_belongs_to_many :exam_appointments, join_table: :users_exam_appointments

  validates_associated :language_grades
  has_many :language_grades, autosave: true
  has_many :exams, through: :language_grades

  def bypass=(bypass)
    @bypass = bypass
  end

  def bypass?
    @bypass
  end

  before_validation :default_role

  def default_role
    self.role ||= Role.user
  end

  def full_name
    "#{name} #{surname}"
  end

  include Concerns::UserValidations
  include Concerns::UserRegistered

  def can_view_grades?
    false
  end

  def staff?
    role_id.in?(1..4)
  end

  state_machine :initial => :registered do
    state all - [:registered] do
      include Concerns::UserProfileFilled
    end
    state :grades_filled, :language_chosen, :language_skipped, :grades_confirmed do
      def can_view_grades?
        true
      end
    end
    state all - [:language_exam_paid] do
      def exam_sign_up(exam)
        false
      end

      def exam_release(exam)
        false
      end
    end
    state :language_exam_paid do
    end

    state :unregistered do
    end
    state :registered do
    end
    state :profile_filled do
    end
    state :cv_uploaded do
    end
    state :grades_filled do
    end
    state :language_chosen do
    end
    state :language_skipped do
    end
    state :grades_confirmed do
    end
    state :language_exam_paid do
      include Concerns::UserLanguageExamPaid
      include Concerns::UserExam
    end
    state :exam_confirmed do
      include Concerns::UserLanguageExamPaid
      include Concerns::UserExamConfirmed
    end
    state :exam_passed do
    end
    state :preliminary_ranking do
    end
    state :ranking do
    end
    state :offers_published do
    end
    state :offer_assigned do
    end
    state :application do
    end
    state :documents_published do
    end
    state :documents_accepted do
    end
    state :suspended do
    end

    # rubocop:disable HashSyntax
    event :sign_up do
      transition :unregistered => :registered
    end
    event :sign_in do
      transition :unregistered => :registered
    end
    event :edit_profile do
      transition :registered => :profile_filled

      transition :profile_filled => same
      transition :cv_uploaded => same
    end
    event :upload_cv do
      transition :profile_filled => :cv_uploaded
    end
    event :edit_grades do
      transition :profile_filled => same
      transition :cv_uploaded => same
    end
    event :lock_profile do
      transition [:cv_uploaded, :profile_filled] => :grades_filled, :if => lambda { |user|
        user.subject_grades.count > 0
      }
    end
    event :unlock_profile do
      transition :grades_filled => :profile_filled
    end
    event :choose_language do
      transition :grades_filled => :grades_filled
    end
    event :lock_language do
      transition :grades_filled => :language_chosen
    end
    event :skip_exam do
      transition :grades_filled => :language_skipped, if: lambda { |user|
        !user.language_passed_exams.empty? and user.language_enrolled_exams.empty?
      }
    end
    # staff only
    event :confirm_grades do
      transition :language_chosen => :grades_confirmed
      transition :language_skipped => :exam_passed
    end
    # manager only
    event :disapprove_grades do
      transition :grades_confirmed => :language_chosen
      transition :exam_passed => :language_skipped
    end
    # staff only
    event :pay_exam_fee do
      transition :grades_confirmed => :language_exam_paid
    end
    event :choose_exam do
      transition :language_exam_paid => same
    end
    event :lock_exam do
      transition :language_exam_paid => :exam_confirmed, :if => lambda { |user|
        !user.language_paid_exams.select(:exam_id).any? { |lg| lg.exam_id.nil? }
      }
    end
    # staff only
    event :upload_positive_language_grade do
      transition :exam_confirmed => :exam_passed
    end
    # staff only
    event :upload_negative_language_grade do
      transition :exam_confirmed => :suspended
    end
    # manager only
    event :publish_preliminary_ranking do
      transition :exam_passed => :preliminary_ranking
    end
    event :complain_about_ranking do
      transition :preliminary_ranking => same
    end
    event :preview_ranking do
      transition :preliminary_ranking => same
    end
    # manager only
    event :publish_ranking do
      transition :preliminary_ranking => :ranking
    end
    event :view_ranking do
      transition :ranking => :ranking
    end
    # manager only
    event :publish_offers do
      transition :ranking => :offers_published
    end
    event :edit_priority do
      transition :offers_published => same
    end
    # manager only
    event :assign_offers do
      transition :offers_published => :offer_assigned
    end
    event :give_up do
      transition :offer_assigned => :suspended
    end
    # staff only
    event :pay_deposit do
      transition :offer_assigned => :application
    end
    event :upload_documents do
      transition :application => same
    end
    event :edit_documents do
      transition :application => same
    end
    event :publish_documents do
      transition :application => :documents_published
    end
    # staff only
    event :send_for_fixes do # TODO: change name
      transition :documents_published => :application
    end
    # staff only
    event :comment_document do # TODO: change name
      transition :documents_published => same
    end
    # staff only
    event :accept_document do
      transition :documents_published => same
    end
    # staff only
    event :accept_application do
      transition :documents_published => :documents_accepted
    end
    event :download_documents do
      transition :documents_accepted => same
    end
  end
  # rubocop:enable HashSyntax

  #@params single role or iterable collection of roles
  #@@return true if user has role in specified range
  def role?(role_symbol)
    return role_symbol.nil? if self.role.nil?

    if role_symbol.respond_to? :detect
      (!role_symbol.detect { |s| s.to_s == self.role.name }.nil?)
    else
      self.role.name == role_symbol.to_s
    end
  end

  private

  def confirmed?
    !confirmed_at.nil?
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_profile

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_profile
    @user = User.find(params[:user_id] || params[:id])

    access_denied! 'cannot.view.user' unless can? :read, @user
  end

  public

  def show
    access_denied! 'cannot.view_profile' unless can? :view_profile, @user
  end

  def edit
    access_denied! 'cannot.edit_profile' unless can? :edit_profile, @user
  end

  def update
    access_denied! 'cannot.edit_profile' unless can? :edit_profile, @user

    form = UserProfileForm.new(@user, params)

    if form.edit_profile
      redirect_to user_path(@user), notice: 'User was successfully updated.'
    else
      unless @user.errors[:sector_priorities].nil?
        @user.errors[:sector_priorities].each { |error| @user.errors[:sector_ids] << error }
      end
      render action: 'edit'
    end
  end

  def lock
    access_denied! 'cannot.lock_profile' if cannot? :lock_profile, @user

    if @user.lock_profile
      redirect_to user_path(@user), notice: 'Profile was successfully locked.'
    else
      redirect_to user_path(@user), flash: {error: 'Profile cannot be locked.'}
    end
  end

  def unlock
    access_denied! 'cannot.unlock_profile' if cannot? :unlock_profile, @user

    if @user.unlock_profile
      redirect_to user_path(@user), notice: 'Profile was unlocked.'
    else
      redirect_to user_path(@user), flash: {error: 'Profile cannot be unlocked.'}
    end
  end

  # staff
  def confirm_grades
    access_denied! 'cannot.confirm_grades' if cannot? :confirm_grades, @user

    @user.confirm_grades

    redirect_to user_path(@user), notice: 'Grades confirmed!'
  end

  def disapprove_grades
    access_denied! 'cannot.disapprove_grades' if cannot? :disapprove_grades, @user

    @user.disapprove_grades

    redirect_to user_path(@user), notice: 'Grades disapproved!'
  end
end

app/views/users/_form.html.slim
= simple_form_for(@user, validate: true, url: user_path(@user), html: {class: 'form-horizontal'}) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name, input_html: {class: 'span5'}
    = f.input :surname, input_html: {class: 'span5'}
    = f.input :email, input_html: {class: 'span5'}
    = f.association :faculty, required: true, input_html: {class: 'span5'}
    = f.association :field_of_study, collection: [], as: :select, disabled: true, required: true, input_html: {class: 'span5'}
    = f.association :specialization, collection: [], as: :select, disabled: true, input_html: {class: 'span5'}
    = f.input :student_no, required: true, input_html: {class: 'span5'}
    = f.input :study_year, as: :select, collection: ['1 - I st.', '2 - I st.', '3 - I st.', '4 - I st.', '1 - II st.', '2 - II st.', 'studia doktoranckie'].map.with_index{ |t, index| [t, index+1] }, required: true, input_html: {class: 'span5'}
    = f.input :street, input_html: {class: 'span5'}
    = f.input :house, required: true, input_html: {class: 'span5'}
    = f.input :city, required: true, input_html: {class: 'span5'}
    = f.input :zip, required: true, input_html: {class: 'span5'}
    = f.input :phone, required: true, input_html: {class: 'span5'}
    = f.input :birth_date, as: :date_picker, start_year: Date.today.year-90, end_year: Date.today.year-12, order: [:day, :month, :year], use_month_numbers: true, required: true, input_html: {class: 'span5'}
    = f.input :sector_ids, collection: SectorGroup.includes(:sectors).load, as: :grouped_select, group_method: :sectors, group_label_method: :name, label_method: :name, required: true, input_html: {multiple: true, class: 'span5'}
  .form-actions
    = f.button :submit, class: 'btn btn-primary'
    '
    = link_to 'Back', user_path(@user), class: 'btn'

  = content_for :js
    = render 'form_widgets', field_of_study_id: @user.field_of_study_id, specialization_id: @user.specialization_id

app/views/users/_form_widgets.html.erb
<%
   field_of_study_id = field_of_study_id.nil? ? 'null' : field_of_study_id
   specialization_id = specialization_id.nil? ? 'null' : specialization_id
%>

<script type="text/javascript">
    $(document).ready(function () {
        $('input.date_picker').datepicker({
            format: 'dd-mm-yyyy',
            startDate: '01-01-1950',
            endDate: '01-01-2013',
            startView: 'decade',
            autoclose: true,
        });

        $('#user_faculty_id').select2({
            dropdownAutoWidth: true,
        });
        $('#user_field_of_study_id').select2({
            dropdownAutoWidth: true,
        });
        $('#user_specialization_id').select2({
            dropdownAutoWidth: true,
            allowClear: true,
        });
        $('#user_study_year').select2({
            dropdownAutoWidth: true,
        });

        $('#user_sector_ids').select2({
            minimumSelectionSize: 1,
            maximumSelectionSize: 3,
        });
        $('#user_field_of_study_id').remoteChained('#user_faculty_id', '/faculties/field_of_studies', <%= field_of_study_id %>);
        $('#user_specialization_id').remoteChained('#user_field_of_study_id', '/faculties/specializations', <%= specialization_id %>);
    })
</script>

app/views/users/edit.html.slim
.page-header
  h1 Editing profile

== render 'form'

app/views/users/show.html.slim
.page-header
  h1 Profile
  - if Rails.env.development?
    h4= @user.state

.container-fluid
  .row
    .span7
      dl.dl-horizontal
        dt= t 'activerecord.attributes.user.name'
        dd= @user.name
        dt= t 'activerecord.attributes.user.surname'
        dd= @user.surname
        dt= t 'activerecord.attributes.user.email'
        dd= @user.email
        dt= t 'activerecord.attributes.user.committee'
        dd= @user.committee.name
        dt= t 'activerecord.models.faculty'
        dd= @user.faculty.try(:name)
        dt= t 'activerecord.models.field_of_study'
        dd= @user.field_of_study.try(:name)
        - if @user.specialization
          dt= t 'activerecord.models.specialization'
          dd= @user.specialization.name
        dt= t 'activerecord.attributes.user.student_no'
        dd= @user.student_no
        dt= t 'activerecord.attributes.user.study_year'
        dd= @user.study_year
        dt= t 'activerecord.attributes.user.street'
        dd= @user.street
        dt= t 'activerecord.attributes.user.house'
        dd= @user.house
        dt= t 'activerecord.attributes.user.city'
        dd= @user.city
        dt= t 'activerecord.attributes.user.zip'
        dd= @user.zip
        dt= t 'activerecord.attributes.user.phone'
        dd= @user.phone
        dt= t 'activerecord.attributes.user.birth_date'
        dd= @user.birth_date
        dt= t 'text.preferable_sectors'
        dd= @user.sectors.map{ |s| s.name }.join(', ')
    .span4
      .container-fluid
        - unless @user.subject_grades.blank?
          .row
            h4 Grades
            = render 'subject_grades/summary', user: @user
        - unless @user.language_passed_exams.blank?
          .row
            h4 Languages previous years
            = render 'language_grades/passed_exams', language_grades: @user.language_passed_exams
        - unless @user.language_enrolled_exams.blank?
          .row
            h4
              'Language Exams -
              = Setting.year(@user.committee_id)
            table.table.table-striped.table-hover
              thead
                tr
                  th.span6= t 'activerecord.attributes.language_grades.language'
                  th.span2= t 'activerecord.attributes.language_grades.paid'
                  th.span2
              tbody
                - @user.language_enrolled_exams.each do |language_grade|
                  tr
                    td= language_grade.language.try(:name)
                    td
                      = check_box_tag "user[language_ids][#{language_grade.id}]", language_grade.language_id, language_grade.paid, disabled: true
                    td= language_grade.grade

  .row
    dl.span12
      .form-actions
        - if can?(:edit_profile, @user)
          = link_to 'Edit', edit_user_path(@user), class: "btn#{' btn-primary' if @user.state == 'registered'}"
          '
        - if can?(:edit_grades, @user)
          = link_to 'Edit Grades', edit_user_subject_grades_path(@user), class: "btn#{' btn-primary' if cannot? :lock_profile, @user}"
          '
        - if can?(:view_grades, @user)
          = link_to 'Show Grades', user_subject_grades_path(@user), class: 'btn'
          '
        - if can?(:lock_profile, @user)
          = link_to 'Lock Profile', user_data_lock_path(@user), method: :patch, class: 'btn btn-primary'
          '
        - if can?(:unlock_profile, @user)
          = link_to 'Unlock Profile', user_data_unlock_path(@user), method: :patch, class: 'btn btn-warning'
          '
        - if can?(:choose_language, @user)
          = link_to 'Choose Languages', user_language_grades_path(@user), class: 'btn btn-primary'
          '
        = link_to 'Back', user_path(@user), class: 'btn btn-success'
        '
        - if can?(:destroy, @user)
          = link_to 'Destroy', user_path(@user), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger'
        '
        - if can? :confirm_grades, @user
          = link_to 'Confirm Grades', user_confirm_grades_path(@user), method: :patch, class: 'btn btn-primary'
          '
        /confirm_grades
        - if can? :disapprove_grades, @user
          = link_to 'Disapprove Grades', user_disapprove_grades_path(@user), method: :patch, class: 'btn'
          '
        - if can? :pay_exam_fee, @user
          = link_to 'Pay Exam Fee', payment_user_language_grades_path(@user), class: 'btn btn-primary'
          '
        - if can? :choose_exam, @user
          = link_to 'Choose exam', user_exams_path(@user), class: "btn #{'btn-primary' if cannot? :lock_exam, @user}"
          '
          - if can? :lock_exam, @user
            = link_to 'Confirm Exams', lock_user_exams_path(@user), class: 'btn btn-primary', method: :patch, data: { confirm: 'Confirming exams disallows to change exam dates. Are you sure you want to continue?' }
            '