config/routes.rb
Soso::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :language_grades

  get 'profile/password'
  get 'faculties/field_of_studies/:faculty_id', to: 'faculties#field_of_studies', as: :faculties_field_of_studies
  get 'faculties/specializations/:field_of_study_id', to: 'faculties#specializations', as: :faculties_specializations

  resources :faqs do
    collection do
      post 'sort'
    end
  end

  root to: 'pages#root'

  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :registration,
             only: [:new, :create, :edit, :update],
             path: 'users',
             path_names: {new: 'sign_up'},
             controller: 'devise/registrations',
             as: :user_registration do
      get :cancel
    end
  end

  resources :users do
    resources :subject_grades do
      collection do
        post 'sort'
        get 'edit'
      end
    end
    resources :language_grades do
      collection do
        post 'enroll', to: 'users#create', as: :enroll
        patch 'lock', as: :lock
        get 'skip', as: :skip

        # staff
        get 'payment'
        patch 'pay'
      end
    end
    resources :exams do
      collection do
        patch 'lock', as: :lock
      end
      member do
        patch 'sign_up'
        patch 'release'
      end
    end
    patch 'lock', to: 'users#lock', as: :data_lock
    patch 'unlock', to: 'users#unlock', as: :data_unlock

    # staff
    patch :confirm_grades, as: :confirm_grades
    patch :disapprove_grades, as: :disapprove_grades
  end

  get 'p/:slug', to: 'pages#show', as: :page
end

app/models/subject_grade.rb
# == Schema Information
# Schema version: 20130830122612
#
# Table name: subject_grades
#
# *id*::         <tt>integer, not null, primary key</tt>
# *user_id*::    <tt>integer, indexed</tt>
# *subject_id*:: <tt>integer, indexed</tt>
# *grade*::      <tt>float</tt>
# *ects*::       <tt>float</tt>
# *created_at*:: <tt>datetime</tt>
# *updated_at*:: <tt>datetime</tt>
#
# Indexes
#
#  index_subject_grades_on_subject_id  (subject_id)
#  index_subject_grades_on_user_id     (user_id)
#--
# == Schema Information End
#++

class SubjectGrade < ActiveRecord::Base
  belongs_to :user
  belongs_to :subject

  after_destroy :destroy_subject_if_not_used

  acts_as_list scope: :user

  validates :grade,
            numericality: {greater_than_or_equal_to: 2, less_than_or_equal_to: 5},
            inclusion: {in: [2, 3, 3.5, 4, 4.5, 5]}

  validates :ects,
            numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 30},
            inclusion: {in: (0.upto(60)).map { |points| points/2.0 }}

  validates :subject, :subject_id, :user, :grade, :ects,
            presence: true

  def destroy_subject_if_not_used
    count = Subject.where(id: self.subject_id).joins(:subject_grades).count
    Subject.delete(self.subject_id) if count == 0
  end
end

app/controllers/subject_grades_controller.rb
class SubjectGradesController < ApplicationController
  before_action :set_user

  before_action :ensure_can_edit_grades, except: [:index]

  def index
    access_denied! 'cannot.view_grades' if cannot? :view_grades, @user

    @subject_grades = @user.subject_grades.order(:position)
    @subjects = Subject.where(committee_id: @user.committee_id).order(:name)
    @subject_grade = SubjectGrade.new
  end

  def edit
    @subject_grades = @user.subject_grades.order(:position)
    @subjects = Subject.where(committee_id: @user.committee_id).order(:name)
    @subject_grade = SubjectGrade.new
  end

  def sort
    grade_ids = params.permit(subject_grade: [])[:subject_grade]
    raise 'Are you kidding me?' if grade_ids.blank?
    grades = SubjectGrade.find(grade_ids)
    raise 'Cannot sort subject of different users!' if grades.map { |g| g.user_id }.uniq.size > 1
    access_denied! 'cannot.edit_grades' if cannot? :edit_grades, grades.first.user

    grades = grades.index_by(&:id)
    grade_ids.each.with_index do |grade_id, index|
      grades[grade_id.to_i].update(position: index + 1)
    end
    render nothing: true
  end

  def create
    sg_params = subject_grade_params(:subject)

    subject = Subject.find_or_create(sg_params[:subject_id], sg_params[:subject], @user.committee_id)

    unless subject.nil?
      access_denied! 'cannot.view.subject' if cannot? :read, subject
    end

    @subject_grade = SubjectGrade.new(user_id: @user.id, grade: sg_params[:grade], ects: sg_params[:ects], subject: subject)

    access_denied! 'cannot.create.subject_grade' if cannot? :create, @subject_grade

    if @subject_grade.save
      redirect_to edit_user_subject_grades_path(@user), notice: 'Subject grade was successfully created.'
    else
      @subject_grades = @user.subject_grades.order(:position)
      @subjects = Subject.where(committee_id: @user.committee_id).order(:name)
      render 'edit'
    end
  end

  def destroy
    @subject_grade = SubjectGrade.find(params[:id])
    access_denied! 'cannot.edit_grades' if cannot? :destroy, @subject_grade

    @subject_grade.destroy

    redirect_to edit_user_subject_grades_path(@user), notice: 'Subject grade was successfully destroyed.'
  end

  private

  def set_user
    @user = User.find(params[:user_id])

    access_denied! 'cannot.view.user' unless can? :read, @user
  end

  def ensure_can_edit_grades
    access_denied! 'cannot.edit_grades' if cannot? :edit_grades, @user
  end

  # Only allow a trusted parameter "white list" through.
  def subject_grade_params(*extra_params)
    permitted = [:subject_id, :grade, :ects]
    extra_params.each { |param| permitted << param }
    params.require(:subject_grade).permit(permitted)
  end
end

app/views/subject_grades/_form.html.slim
= simple_form_for(@subject_grade, remote: false, validate: true, url: user_subject_grades_path(@user), \
    html: {class: 'form-horizontal'}) do |f|
  = f.error_notification
  .form-inputs
    = f.input :subject, as: :hidden
    = f.input :subject_id, input_html: {data: {subjects: @subjects.map{ |i|i.as_json only: [:id,:name]}} }, required: true

    = f.input :grade, :collection => [2.0, 3.0, 3.5, 4.0, 4.5, 5.0].reverse, required: true
    = f.input :ects, required: true, input_html: {min: 0.0, max: 30.0, step: 1}

  .form-actions
    = f.button :submit, 'Add', class: 'btn btn-primary'
    = link_to 'Back', user_path(@user), class: 'btn'

= content_for :js
  coffee:
    jQuery ->
      SubjectGrades.init_subject_select2()

      $('#subject_grade_grade').select2({
        dropdownAutoWidth: true
      })

app/views/subject_grades/_summary.html.slim
dl.dl-horizontal
  dt= t 'activerecord.attributes.subject_grades.average'
  dd#user_grades_average= user.pretty_average
  dt= t 'activerecord.attributes.subject_grades.ects'
  dd#user_ects_sum= user.sum_ects

app/views/subject_grades/_table.html.slim
table#user_grades.table.table-striped.table-hover
  caption
    | enter all subjects bla bla
  thead
    tr
      th= t 'activerecord.attributes.subject_grades.subject'
      th= t 'activerecord.attributes.subject_grades.grade'
      th= t 'activerecord.attributes.subject_grades.ects'
      - if show_delete
        th
  tbody data-update-url="#{sort_user_subject_grades_path}"
    - subject_grades.each do |subject_grade|
      tr id="subject_grade_#{subject_grade.id}" data-grade=subject_grade.grade data-ects=subject_grade.ects
        td= subject_grade.subject.try(:name)
        td= subject_grade.grade
        td= subject_grade.ects
        - if show_delete
          td.actions
            span.actions
              = link_to '<i class="icon-trash"/>'.html_safe, user_subject_grade_path(@user, subject_grade), method: :delete, data: { confirm: 'Are you sure?' }

app/views/subject_grades/edit.html.slim
.page-header
  h1 Grades

.row
  .span10
  - unless @subject_grades.blank?
    .span10
      = render 'table', subject_grades: @subject_grades, show_delete: true

      = render 'summary', user: @user

= content_for :js
  coffee:
    jQuery ->
      SubjectGrades.sortableList('#user_grades > tbody')
      SubjectGrades.recalculate()

.row
  #subject_grade_form_box.span10
    = render 'form', subject_grade: @subject_grade

app/views/subject_grades/index.html.slim
.page-header
  h1 Grades

.row
  .span10
  - unless @subject_grades.blank?
    .span10
      = render 'table', subject_grades: @subject_grades, show_delete: false

      = render 'summary', user: @user

= content_for :js
  coffee:
    jQuery ->
      SubjectGrades.recalculate()

.row
  .span10
    form
      .form-actions
        = link_to 'Back', user_path(@user), class: 'btn'
        '
        - if can? :confirm_grades, @user
          = link_to 'Confirm Grades', user_confirm_grades_path(@user), method: :patch, class: 'btn btn-primary'
          '
        /confirm_grades
        - if can? :disapprove_grades, @user
          = link_to 'Disapprove Grades', user_disapprove_grades_path(@user), method: :patch, class: 'btn'
          '