config/routes.rb
Soso::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :language_grades

  get 'profile/password'
  get 'faculties/field_of_studies/:faculty_id', to: 'faculties#field_of_studies', as: :faculties_field_of_studies
  get 'faculties/specializations/:field_of_study_id', to: 'faculties#specializations', as: :faculties_specializations

  resources :faqs do
    collection do
      post 'sort'
    end
  end

  root to: 'pages#root'

  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :registration,
             only: [:new, :create, :edit, :update],
             path: 'users',
             path_names: {new: 'sign_up'},
             controller: 'devise/registrations',
             as: :user_registration do
      get :cancel
    end
  end

  resources :users do
    resources :subject_grades do
      collection do
        post 'sort'
        get 'edit'
      end
    end
    resources :language_grades do
      collection do
        post 'enroll', to: 'users#create', as: :enroll
        patch 'lock', as: :lock
        get 'skip', as: :skip

        # staff
        get 'payment'
        patch 'pay'
      end
    end
    resources :exams do
      collection do
        patch 'lock', as: :lock
      end
      member do
        patch 'sign_up'
        patch 'release'
      end
    end
    patch 'lock', to: 'users#lock', as: :data_lock
    patch 'unlock', to: 'users#unlock', as: :data_unlock

    # staff
    patch :confirm_grades, as: :confirm_grades
    patch :disapprove_grades, as: :disapprove_grades
  end

  get 'p/:slug', to: 'pages#show', as: :page
end

app/models/committee.rb
# == Schema Information
# Schema version: 20130817211608
#
# Table name: committees
#
# *id*::      <tt>integer, not null, primary key</tt>
# *name*::    <tt>string(255), not null, indexed => [city_id]</tt>
# *code*::    <tt>string(255)</tt>
# *city_id*:: <tt>integer, indexed, indexed => [name]</tt>
#
# Indexes
#
#  index_committees_on_city_id           (city_id)
#  index_committees_on_city_id_and_name  (city_id,name) UNIQUE
#--
# == Schema Information End
#++

class Committee < ActiveRecord::Base
  delegate :country, to: :city, allow_nil: true
  belongs_to :city
  has_many :users
  # has_many :news
  # has_many :faqs
  # has_many :appointment
  has_many :faculties
  has_and_belongs_to_many :languages
  has_many :exams

  validates :name,
            presence: true,
            uniqueness: {scope: :city_id}
  validates :city_id,
            presence: true,
            numericality: {only_integer: true}
end

app/models/exam.rb
# == Schema Information
# Schema version: 20131010090254
#
# Table name: exams
#
# *id*::           <tt>integer, not null, primary key</tt>
# *language_id*::  <tt>integer, indexed</tt>
# *datetime*::     <tt>datetime</tt>
# *min*::          <tt>integer</tt>
# *max*::          <tt>integer</tt>
# *state*::        <tt>string(255)</tt>
# *committee_id*:: <tt>integer, indexed</tt>
# *created_at*::   <tt>datetime</tt>
# *updated_at*::   <tt>datetime</tt>
#
# Indexes
#
#  index_exams_on_committee_id  (committee_id)
#  index_exams_on_language_id   (language_id)
#--
# == Schema Information End
#++

class Exam < ActiveRecord::Base
  STATES = [:open, :close, :canceled, :confirmed]

  has_many :language_grades
  belongs_to :committee
  belongs_to :language

  validates :committee,
            presence: true
  validates :language,
            presence: true
  validates :state,
            presence: true,
            inclusion: {in: STATES}
  validates :min,
            presence: true,
            numericality: {only_integer: true, less_than_or_equal_to: :max}
  validates :max,
            presence: true,
            numericality: {only_integer: true, greater_than_or_equal_to: :max}

  def name
    if self.language
      self.language.name+', '+self.datetime.strftime('%d.%m %H:%M')
    else
      self.datetime.strftime('%d.%m %H:%M')
    end
  end

  def state
    read_attribute(:state).to_sym
  end

  def state=(value)
    write_attribute(:state, value.to_s)
  end

  def self.available(user)
    user_id, committee_id = user.id, user.committee_id

    Exam.
        joins(language: :language_grades).
        includes(:language).
        includes(:language_grades).
        where(language_grades: {user_id: user_id, grade: nil, year: Setting.year(committee_id), paid: true},
              exams: {committee_id: committee_id, state: :open})
  end

  def places
    # .size instead of .count because :language_grades are included in join
    places = {min: self.min, max: self.max, occupied: self.language_grades.size}
    places[:left] = places[:max] - places[:occupied]
    places
  end

  def calendar_event
    {
        id: self.id,
        language_name: self.language.try(:name),
        language_id: self.language_id,
        start: self.datetime.to_i,
        end: (self.datetime + 1.hour).to_i,
        places: self.places
    }
  end

  def places_left
    self.max - self.language_grades.count
  end

  def signed_up?(user_id)
    user_id = user_id.id if user_id.is_a? User

    self.language_grades.includes(:user).where(user_id: user_id).count > 0
  end
end

app/models/language_grade.rb
# == Schema Information
# Schema version: 20131010090254
#
# Table name: language_grades
#
# *id*::          <tt>integer, not null, primary key</tt>
# *user_id*::     <tt>integer, indexed => [language_id], indexed => [language_id, year], indexed</tt>
# *language_id*:: <tt>integer, indexed, indexed => [user_id], indexed => [user_id, year]</tt>
# *grade*::       <tt>float</tt>
# *year*::        <tt>integer, indexed => [language_id, user_id]</tt>
# *paid*::        <tt>boolean</tt>
# *created_at*::  <tt>datetime</tt>
# *updated_at*::  <tt>datetime</tt>
# *exam_id*::     <tt>integer, indexed</tt>
#
# Indexes
#
#  index_language_grades_on_exam_id                           (exam_id)
#  index_language_grades_on_language_id                       (language_id)
#  index_language_grades_on_language_id_and_user_id           (language_id,user_id)
#  index_language_grades_on_language_id_and_user_id_and_year  (language_id,user_id,year) UNIQUE
#  index_language_grades_on_user_id                           (user_id)
#--
# == Schema Information End
#++

class LanguageGrade < ActiveRecord::Base
  # +year+ is always set to +Setting.year+
  # +user_id+, +language_id+ and +year+ cannot be +NULL+
  #
  # Only one language per user per year is possible.
  #
  # If +grade = nil+ then entity is a sign up for an exam
  # otherwise it is a grade for written exam.
  belongs_to :user
  belongs_to :language
  belongs_to :exam

  validates :grade,
            numericality: {greater_than_or_equal_to: 2, less_than_or_equal_to: 5},
            allow_blank: true
  validates :year,
            uniqueness: {scope: [:language_id, :user_id]}
  validates :user_id, :language_id, :year,
            presence: true

  def self.has_paid user_id
    user = User.find(user_id)
    not LanguageGrade.where(user_id: user.id, paid: true, year: Setting.year(user.committee_id)).empty?
  end

  def self.has_selected(user_id)
    user = User.find(user_id)
    not LanguageGrade.where(user_id: user.id, grade: nil, year: Setting.year(user.committee_id)).empty?
  end
end

app/controllers/language_grades_controller.rb
class LanguageGradesController < ApplicationController
  before_action :set_user

  def index
    access_denied! 'cannot.choose_language' if cannot? :choose_language, @user

    @language_grades = @user.language_grades.where('grade IS NOT NULL')
    language_grades = @user.language_grades.where('grade IS NULL')
    @languages = @user.committee.languages.map do |language|
      lgs = language_grades.select { |lg| lg.language_id == language.id }
      {
          language: language,
          checked: !lgs.empty?,
          paid: lgs.detect { |lg| lg.paid }
      }
    end
  end

  def update
    language_ids = user_language_grades_params[:language_ids]
    language_ids = [] if language_ids.nil?

    access_denied! 'cannot.choose_language' if cannot? :choose_language, @user

    languages = Language.find(language_ids)
    access_denied! 'cannot.choose_language' if languages.detect { |lang| cannot? :choose, lang }

    @user.language_choices(languages)

    respond_to do |format|
      if @user.save
        format.json { render json: {success: true} }
      else
        format.json { render json: {success: false, errors: @user.errors} }
      end
    end
  end

  def destroy
    @language_grade.destroy
    redirect_to language_grades_url, notice: 'Language grade was successfully destroyed.'
  end

  def lock
    access_denied! 'cannot.lock_language' if cannot? :lock_language, @user

    @user.lock_language

    redirect_to page_path('payment'), notice: 'Your language choice was permanently saved.'
  end

  # staff

  def payment
    access_denied! 'cannot.pay_exam_fee' if cannot? :pay_exam_fee, @user

    @language_grades = @user.language_enrolled_exams
    redirect_to user_path(@user), flash: {error: 'User has not signed up for any exam!'} if @language_grades.empty?
  end

  def skip
    access_denied! 'cannot.skip_exam' if cannot? :skip_exam, @user
  end

  def pay
    language_grade_ids = params.require(:user).permit(:id, language_grade_ids: [])[:language_grade_ids]
    language_grade_ids = [] if language_grade_ids.nil?
    language_grade_ids.map!(&:to_i)

    access_denied! 'cannot.pay_exam_fee' if cannot? :pay_exam_fee, @user

    @language_grades = @user.language_enrolled_exams
    if @language_grades.blank?
      redirect_to user_path(@user), flash: {error: 'User has not signed up for any exam!'}
    else
      @user.language_grades.map! do |language_grade|
        if language_grade.id.in? @language_grades.map(&:id)
          access_denied! 'cannot.view.language_grade' if cannot? :update, language_grade
          language_grade.paid = language_grade.id.in? language_grade_ids
          language_grade.save
        end
        language_grade
      end

      if @user.pay_exam_fee
        redirect_to user_path(@user), notice: 'Language exam fees have been paid!'
      else
        render action: :payment
      end
    end
  end

  private
  
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:user_id])

    access_denied! 'cannot.view.user' unless can? :read, @user
  end

  def user_language_grades_params
    params.require(:user).permit(:id, language_ids: [])
  end
end

app/helpers/language_grades_helper.rb
module LanguageGradesHelper
  def onoff_tag(name, value = '1', checked = false, options = {})
    html_options = {type: 'checkbox', name: name, id: sanitize_to_id(name), value: value, class: 'onoffswitch-checkbox'}.update(options.stringify_keys)
    html_options['checked'] = 'checked' if checked
    content_tag :div, class: 'onoffswitch' do
      tag(:input, html_options) +
          content_tag(:label, '', class: 'onoffswitch-label', for: name) do
            content_tag(:div, '', class: 'onoffswitch-inner') +
                content_tag(:div, '', class: 'onoffswitch-switch')
          end
    end
  end
end

app/views/language_grades/_form.html.slim
= simple_form_for(@language_grade) do |f|
  = f.error_notification

  .form-inputs
    = f.association :user, autofocus: true
    = f.association :language
    = f.input :grade
    = f.input :year
    = f.input :paid

  .form-actions
    = f.button :submit, class: 'btn btn-primary'
    '
    = link_to 'Back', language_grades_path, class: 'btn'

app/views/language_grades/_passed_exams.html.slim
table#user_passed_languages.table.table-striped.table-hover
  thead
    tr
      th= t 'activerecord.attributes.language_grades.language'
      th= t 'activerecord.attributes.language_grades.grade'
      th= t 'activerecord.attributes.language_grades.year'
  tbody
    - language_grades.each do |language_grade|
      tr id="subject_grade_#{language_grade.id}"
        td= language_grade.language.try(:name)
        td= language_grade.grade
        td= language_grade.year

app/views/language_grades/index.html.slim
.page-header
  h1 Languages

.row
  .span6
    h4 Sign up for an exam
    = simple_form_for(@user, url: enroll_user_language_grades_path(@user), remote: true,  html: {class: 'user-form form-vertical'}) do |f|
      .form-inputs
        = f.input :id, as: :hidden
        table#user_language_exams.table.table-striped.table-hover
          /caption
          thead
            tr
              th.span10= t 'activerecord.attributes.language_grades.language'
              th.span1
              th.span1
          tbody
            - @languages.each do |language_hash|
              - language = language_hash[:language]
              - paid = language_hash[:paid]
              - checked = language_hash[:checked]
              tr.checkbox id="tr_language_#{language.id}"
                td= language.try(:name)
                td
                  - if paid
                    = check_box_tag "user[language_ids][#{language.id}]", language.id, checked, disabled: true, class: 'paid'
                    |paid
                  - else
                    = check_box_tag "user[language_ids][#{language.id}]", language.id, checked
                td
                  span.preloader.hidden
    .form-actions
      - if @user.language_passed_exams.empty?
        = form_tag lock_user_language_grades_path(@user), method: :patch
          = button_tag 'Take Exam', id: 'take_exam_button', class: 'btn btn-primary', data: { confirm: 'Are you sure?' }
      - else
        - allow_skip = @user.language_paid_exams.empty?
        = form_tag lock_user_language_grades_path(@user), method: :patch
          = button_tag 'Improve Your Score', id: 'take_exam_button', class: 'btn' + (if allow_skip then '' else ' btn-primary' end)
        - if allow_skip
          = form_tag skip_user_language_grades_path(@user), method: :get
            = button_tag 'Skip Exam', id: 'skip_exam_button', class: 'btn btn-primary', data: { confirm: 'Are you sure?' }
      = link_to 'Back', user_path(@user), class: 'btn'

  - unless @language_grades.blank?
    .span4
      h4 Grades from previous years
      = render 'passed_exams', language_grades: @language_grades

= content_for :js
  coffee:
    jQuery ->
      LanguageGrade.initDisabledLinks()
      LanguageGrade.formId = '#' + $('.user-form').prop('id')
      LanguageGrade.initButtons('#take_exam_button', '#skip_exam_button')
      LanguageGrade.initRowCheck()
      LanguageGrade.initFormSubmit()
      LanguageGrade.refreshButtons()

app/views/language_grades/payment.html.slim
.page-header
  h1 Languages

.row
  .span6
    h4 Pay exam fee
    = simple_form_for(@user, url: pay_user_language_grades_path(@user), html: {class: 'user-form form-vertical'}) do |f|
      = f.error_notification
      = @user.errors.messages.inspect
      .form-inputs
        = f.input :id, as: :hidden
        table#user_pay_exam_fees.table.table-striped.table-hover
          thead
            tr
              th.span10= t 'activerecord.attributes.language_grades.language'
              th.span1
          tbody
            - @language_grades.each do |language_grade|
              tr.checkbox id="tr_language_grade_#{language_grade.id}"
                td= language_grade.language.try(:name)
                td
                  = check_box_tag 'user[language_grade_ids][]', language_grade.id, language_grade.paid
        = f.button :submit, 'Confirm', id: 'confirm_payment_button', disabled: false, class: 'btn btn-primary'
        = link_to 'Back', user_path(@user), class: 'btn'

= content_for :js
  coffee:
    jQuery ->
      LanguageGrade.initDisabledLinks()
      LanguageGrade.formId = '#' + $('.user-form').prop('id')
      LanguageGrade.initRowCheck()
      LanguageGrade.initConfirmButton('#confirm_payment_button')
      LanguageGrade.initConfirmFormSubmit()
      LanguageGrade.refreshConfirmButton()