config/routes.rb
Soso::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :language_grades

  get 'profile/password'
  get 'faculties/field_of_studies/:faculty_id', to: 'faculties#field_of_studies', as: :faculties_field_of_studies
  get 'faculties/specializations/:field_of_study_id', to: 'faculties#specializations', as: :faculties_specializations

  resources :faqs do
    collection do
      post 'sort'
    end
  end

  root to: 'pages#root'

  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :registration,
             only: [:new, :create, :edit, :update],
             path: 'users',
             path_names: {new: 'sign_up'},
             controller: 'devise/registrations',
             as: :user_registration do
      get :cancel
    end
  end

  resources :users do
    resources :subject_grades do
      collection do
        post 'sort'
        get 'edit'
      end
    end
    resources :language_grades do
      collection do
        post 'enroll', to: 'users#create', as: :enroll
        patch 'lock', as: :lock
        get 'skip', as: :skip

        # staff
        get 'payment'
        patch 'pay'
      end
    end
    resources :exams do
      collection do
        patch 'lock', as: :lock
      end
      member do
        patch 'sign_up'
        patch 'release'
      end
    end
    patch 'lock', to: 'users#lock', as: :data_lock
    patch 'unlock', to: 'users#unlock', as: :data_unlock

    # staff
    patch :confirm_grades, as: :confirm_grades
    patch :disapprove_grades, as: :disapprove_grades
  end

  get 'p/:slug', to: 'pages#show', as: :page
end

app/views/layouts/application.html.slim
doctype 5
html
  head
    title SOSO
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag    'application-scss', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag    'application-css', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    = csrf_meta_tag
    = analytics_init if Rails.env.production?
  body id=(controller.controller_name) class=(controller.action_name)
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          button.btn.btn-navbar[type="button" data-toggle="collapse" data-target=".nav-collapse"]
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.brand[href="#"]
            | SOSO
          .nav-collapse.collapse
            ul.nav
              li= nav_link_to 'Dashboard', root_path if can? :read, :news
              li= nav_link_to 'News', '#' if can? :read, :news
              li= nav_link_to 'FAQ', faqs_path if can? :read, Faq
              - pages = Page.where(slug: %w(in-the-pill terms contact site))
              - if pages.any? { |page| can? :read, page }
                li.dropdown
                  a.dropdown-toggle[href="#" data-toggle="dropdown"]
                    | About
                    b.caret
                  ul.dropdown-menu
                    - Page.where(slug: %w(in-the-pill terms contact site)).each do |page|
                      - if can? :read, page
                        li= nav_link_to page.title, page_path(page.slug)
              li= link_to 'Ranking', '#' if can? :read, :ranking
              li= link_to 'Offers', '#' if can? :read, :offers
            form.navbar-form.pull-right
              ul.nav
                - if can?(:access, :rails_admin)
                  li.dropdown
                    a.dropdown-toggle[href="#" data-toggle="dropdown"]
                      | Admin
                      b.caret
                    ul.dropdown-menu
                      li= link_to('Dashboard', rails_admin_path)
                      li= link_to('Users', '#')
                - if current_user
                  li.dropdown
                    a.dropdown-toggle[href="#" data-toggle="dropdown"]
                      = current_user.email
                      b.caret
                    ul.dropdown-menu
                      li= nav_link_to('Profile', user_path(current_user))
                      li.divider
                      li= nav_link_to('Change password', edit_user_registration_path)
                      li= link_to 'Sign Out', destroy_user_session_path, method: :delete
                - else
                  li= link_to 'Sign In', new_user_session_path

    .wrapper
      - flash.each do |name, msg|
        = content_tag :div, raw(msg), class: "alert #{alert_class(name)}"

      = yield

    .push

    footer
      .container
        p &copy; 2013 All rights reserved.
        p
          a[href='#'] Michał Knapik


  = yield :js